sudo: false
dist: trusty
language: php

env:
  global:
    - COMPOSER_ARGS="--no-interaction"
    - OPENCART_URL=http://127.0.0.1
    - github_token: ${GITHUB_TOKEN}

matrix:
  allow_failures:
    - stage: acceptance-test
  include:
    - php: 5.6
      if: type = cron
    - php: 7.0
      if: type = cron
    - php: 7.1
      if: type = cron
    - &acceptance-test
      stage: acceptance-test
      if: type != cron
      php: 7.1
      env: GATEWAY=API-TEST
      install:
      - chmod +x .bin/*
      - travis_retry composer global require "hirak/prestissimo:^0.3"
      - travis_retry composer require --dev $COMPOSER_ARGS codeception/codeception:^2.5
      - travis_retry composer install $COMPOSER_ARGS
      - composer show
      before_script:
      - export VERSION=`cat SHOPVERSIONS | jq -r '.[0] | .release'`
      - bash ./.bin/start-shopsystem.sh
      - bash ./.bin/start-browserstack.sh
      - travis_retry bash ./.bin/install-extension-ui.sh
      script: system/library/bin/codecept run acceptance -g ui_test --html --xml
      after_script: skip
      after_success:
      - bash .bin/upload-logs-and-notify.sh
      after_failure:
      - bash .bin/upload-logs-and-notify.sh fail
#    - <<: *acceptance-test
#      env: GATEWAY=API-WDCEE-TEST
#    - <<: *acceptance-test
#      env: GATEWAY=NOVA


install:
  - travis_retry composer install $COMPOSER_ARGS
  - composer show

script:
  - composer test-coverage
  - composer cs-check

after_script:
  - travis_retry composer upload-coverage
  - bash .bin/generate-tag.sh

before_deploy:
  - export REPO_NAME=`echo $TRAVIS_REPO_SLUG | awk -F'/' '{print $2}'`
  - export RELEASE_NOTES=$(composer make-release-notes)
  - bash .bin/generate-wiki-notes.sh
  - bash .bin/generate-readme-badge.sh
  - bash .bin/generate-release-package.sh $TRAVIS_TAG

deploy:
  provider: releases
  api_key:
    secure: NNe7dKhfEjPOW3sMUdGk7AD+l7Z9uonBLPZsV2uV+cdeiWoYlEvyBBhjGEHuFNdPBJENaofF7dkRDxaYrI2nIHAQCv539AuvDwfY1Q75iLskUOlvGfe35Bwu/cpZsW6o26PIV+UEpy3wmZvuIiHeF68n9pWXo3Tv6NS+iRt/nC7Wd3meEQZZyKuKaTieKa53bIop1P3bb0yYWb6PpEzOZb4P98F7tmHV8dcHVTUF7XtFsbmmGfByVuNp6ancrcwWELUJ6TpWTUAxAWlGAaKA3BkMKdsN6de+uHM+AF+G8m9s2kR5XWF/33N0tW6lAH6t91F/iG9go9q+ovlhjZRzodXSD04uV4w+S1CSSpFRTM4gKSvW8TxYVhL/YQNhJwb1qw3M5wKoqFMJcw0Zt0tpUFuy2pF8AzCjSIA0O1X4IWviB8TS7bAYtg85GaCGQ9MOPLo7eVu2o3vtCCQgoQjOZ8WLXDGOtCyR4nViJtDGKdZEsJxy4twELZFe0QwiZaVcGWijaCL6SpGfc2FD3dAJo3P9iyIZ4Q56yAfOmN6rIVjNp7mp6yym84lu66E2BsR/cVb7oipb4dBKjN5tk5KaabFgAoc+Low9Xmpg7ntuc92qUr9Vj2NhFJmmXMXRcjBDJC/7WQUgrQk4a6CIefkL0ond0dn6E0yc/3L8eW054v8=
  file: opencart-ee.ocmod.zip
  name: "${REPO_NAME} ${TRAVIS_TAG}"
  body: "${RELEASE_NOTES}"
  skip_cleanup: true
  on:
    repo: ${TRAVIS_REPO_SLUG}
    tags: true

notifications:
  email: false
  slack:
    rooms:
      secure: YI7sUrfMyKyJD60kElGkO7yBDkGEh+069yS8bFAIDUST7s48J+dDP/r2G9dN9oQwhs9hvNjpNytpZDPys838T+Z0mNtFZ9Wu022hV3MpbKUuMl7L9P0MQQmxjg4bKyKK3Hl9tPrZ3UsKRlwIUmRGGYQ7cjs4zumorqs19YsB3X+WnnxAmmYB3kHQYfNKgVnmcG2QHJyx5KaLZ0EsWynSHXkYb8bVCtdlbQFNnpChvGHPprZrHAszLCYnlU7AEZGdbuk17oIfXO9Wjuu1GV8iJ2VgKkTCzW4FBC5eHJyZezojPFUm1I5tvdihRZuyBekVGOF23J6pvHLqPx77clT+/Vn6T+UMDuh1INZ0LKt4UOU42oEDKGblWZx2VYWcHwfEK+ckJWZkT9EBfg/CMenJly2tbtBj6++XNvxgGEDn6XqKIEatcb7X/aiy4f8BPXa3/pzgZAlvzZbGGqHFNZPAlgcXBBXgbaC7VvMhvi6Z5AG5ylKzPS5GCD95ozPC+cGv0234TBJus5oZck4qNiT53IUQ7Ta+OGVB0Mea105VAoQI0I7YcgaqW6c4h2YTmnuuQsIzAwPOrJ5TAinj8Z8mZ9C11tEcNF3Pgy1tOoG/YLurhOJm7v1ebotRb/DIeSHU8RfNatnDSSky4YS6Y8k2pQthdC9m7m2f2mJYuGdLjlM=
    template:
      - "%{repository}#%{build_number} (%{branch} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
    on_success: change
    on_failure: change
